{
  lib,
  runCommand,
  nixPortableX64,
  nixPortableArm64,
  version,
}:
let
  scope = "@cardelli";
  metaPackage = "nix";
  x64Package = "nix-linux-x64";
  arm64Package = "nix-linux-arm64";
  launcher = ../npm/nix/bin/nix.js;

  packageJson = attrs: builtins.toJSON attrs;

  bins = {
    nix = "bin/nix.js";
    nix-portable = "bin/nix.js";
    nix-build = "bin/nix.js";
    nix-channel = "bin/nix.js";
    nix-collect-garbage = "bin/nix.js";
    nix-copy-closure = "bin/nix.js";
    nix-daemon = "bin/nix.js";
    nix-env = "bin/nix.js";
    nix-hash = "bin/nix.js";
    nix-instantiate = "bin/nix.js";
    nix-prefetch-url = "bin/nix.js";
    nix-shell = "bin/nix.js";
    nix-store = "bin/nix.js";
  };
in
runCommand "nix-portable-npm-dist-${version}" {} ''
  mkdir -p "$out/packages/${metaPackage}/bin"
  cp ${launcher} "$out/packages/${metaPackage}/bin/nix.js"
  chmod 755 "$out/packages/${metaPackage}/bin/nix.js"
  cat > "$out/packages/${metaPackage}/package.json" <<'JSON'
${packageJson {
  name = "${scope}/${metaPackage}";
  inherit version;
  description = "Run nix-portable from npm on Linux x64 and arm64.";
  license = "MIT";
  repository = {
    type = "git";
    url = "git+https://github.com/DavHau/nix-portable.git";
  };
  homepage = "https://github.com/DavHau/nix-portable#readme";
  bugs = {
    url = "https://github.com/DavHau/nix-portable/issues";
  };
  bin = bins;
  files = [
    "bin/nix.js"
  ];
  optionalDependencies = {
    "${scope}/${x64Package}" = version;
    "${scope}/${arm64Package}" = version;
  };
}}
JSON

  mkdir -p "$out/packages/${x64Package}/bin"
  cp ${nixPortableX64}/bin/nix-portable "$out/packages/${x64Package}/bin/nix-portable"
  chmod 755 "$out/packages/${x64Package}/bin/nix-portable"
  cat > "$out/packages/${x64Package}/package.json" <<'JSON'
${packageJson {
  name = "${scope}/${x64Package}";
  inherit version;
  description = "Linux x64 nix-portable binary for ${scope}/${metaPackage}.";
  license = "MIT";
  os = [ "linux" ];
  cpu = [ "x64" ];
  files = [
    "bin/nix-portable"
  ];
}}
JSON

  mkdir -p "$out/packages/${arm64Package}/bin"
  cp ${nixPortableArm64}/bin/nix-portable "$out/packages/${arm64Package}/bin/nix-portable"
  chmod 755 "$out/packages/${arm64Package}/bin/nix-portable"
  cat > "$out/packages/${arm64Package}/package.json" <<'JSON'
${packageJson {
  name = "${scope}/${arm64Package}";
  inherit version;
  description = "Linux arm64 nix-portable binary for ${scope}/${metaPackage}.";
  license = "MIT";
  os = [ "linux" ];
  cpu = [ "arm64" ];
  files = [
    "bin/nix-portable"
  ];
}}
JSON

  cat > "$out/README.md" <<'EOF'
  This directory is generated by `nix build .#npm-dist`.

  Publish order:
  1. packages/nix-linux-x64
  2. packages/nix-linux-arm64
  3. packages/nix
  EOF
''
